module.exports = [
  ["pre-authorized withdrawal", "direct debit"],
  ["pre-authorized payment", "direct debit"],
  ["rube goldberg machine", "Heath Robinson device"],
  ["rube goldberg device", "Heath Robinson device"],
  ["dishwashing liquid", "washing-up liquid"],
  ["bedroom community", "dormitory town"],
  ["district attorney", "Crown Prosecutor"],
  ["self-rising flour", "self-raising flour"],
  ["checking account", "current account"],
  ["counterclockwise", "anti-clockwise"],
  ["driver's license", "driving licence"],
  ["general delivery", "poste restante"],
  ["learner's permit", "provisional driving licence"],
  ["sedan automobile", "saloon"],
  ["discombobulated", "discomposed"],
  ["divided highway", "dual carriageway"],
  ["emergency brake", "handbrake"],
  ["shredded cheese", "grated cheese"],
  ["canadian bacon", "back bacon"],
  ["certified mail", "recorded delivery"],
  ["charge account", "credit account"],
  ["driver license", "driving licence"],
  ["eminent domain", "compulsory purchase"],
  ["parking garage", "car park"],
  ["powdered sugar", "icing sugar"],
  ["public holiday", "bank holiday"],
  ["travel trailer", "caravan"],
  ["acetaminophen", "paracetamol"],
  ["baby carriage", "pram"],
  ["blood sausage", "black pudding"],
  ["candied apple", "toffee apple"],
  ["costume party", "fancy-dress party"],
  ["license plate", "number plate"],
  ["station wagon", "estate car"],
  ["variety meats", "offal"],
  ["cotton candy", "candy floss"],
  ["french fries", "chips"],
  ["french press", "cafetière"],
  ["mail carrier", "postal worker"],
  ["mass transit", "public transport"],
  ["nightcrawler", "earthworm"],
  ["off-the-rack", "off-the-peg"],
  ["penitentiary", "prison"],
  ["plastic wrap", "cling-film"],
  ["spring break", "Easter holiday"],
  ["steam shovel", "digger"],
  ["stool pigeon", "grass"],
  ["teleprompter", "compare autocue"],
  ["yellow light", "amber"],
  ["candy apple", "toffee apple"],
  ["garbage can", "dustbin"],
  ["ground beef", "mince"],
  ["heavy cream", "double cream"],
  ["license tag", "number plate"],
  ["main street", "high street"],
  ["paper route", "paper round"],
  ["parking lot", "car park"],
  ["scotch tape", "Sellotape"],
  ["scuttlebutt", "rumour"],
  ["turn signal", "turn-indicators"],
  ["wastebasket", "wastepaper basket"],
  ["bookmobile", "mobile library"],
  ["burglarize", "burgle"],
  ["cell phone", "mobile"],
  ["dish towel", "tea towel"],
  ["expressway", "motorway"],
  ["fanny pack", "bum bag"],
  ["flashlight", "torch"],
  ["front desk", "reception"],
  ["hard candy", "boiled sweets"],
  ["jackhammer", "pneumatic drill"],
  ["laundromat", "laundrette"],
  ["nightstick", "truncheon"],
  ["oftentimes", "often"],
  ["play hooky", "bunk off"],
  ["saran wrap", "cling film"],
  ["spelunking", "caving"],
  ["stickshift", "gear stick"],
  ["stop light", "traffic light"],
  ["sweatpants", "track bottoms"],
  ["track meet", "athletics meeting"],
  ["vacationer", "holidaymaker"],
  ["windshield", "windscreen"],
  ["acclimate", "acclimatise"],
  ["baseboard", "skirting board"],
  ["bleachers", "stands"],
  ["boardwalk", "promenade"],
  ["bobby pin", "Kirby grip"],
  ["cellphone", "mobile"],
  ["chapstick", "lip balm"],
  ["coveralls", "overalls"],
  ["dish soap", "washing-up liquid"],
  ["doohickey", "wotsit"],
  ["downspout", "drainpipe"],
  ["drugstore", "chemist"],
  ["mortician", "undertaker"],
  ["obligated", "obliged"],
  ["pantyhose", "tights"],
  ["plexiglas", "Perspex"],
  ["skim milk", "skimmed milk"],
  ["specialty", "speciality"],
  ["streetcar", "tram"],
  ["swap meet", "car boot sale"],
  ["thumbtack", "drawing pin"],
  ["band-aid", "Elastoplast"],
  ["barrette", "hair slide"],
  ["blacktop", "tarmac"],
  ["blinders", "blinkers"],
  ["breadbox", "bread bin"],
  ["bullhorn", "loudhailer"],
  ["checkers", "draughts"],
  ["cilantro", "coriander"],
  ["dumpster", "skip"],
  ["eggplant", "aubergine"],
  ["envision", "to envisage"],
  ["flatware", "cutlery"],
  ["freshman", "fresher"],
  ["frosting", "icing"],
  ["gasoline", "petrol"],
  ["overpass", "flyover"],
  ["popsicle", "ice lolly"],
  ["rowhouse", "terraced house"],
  ["rutabaga", "swede"],
  ["scallion", "spring onion"],
  ["sidewalk", "pavement"],
  ["sneakers", "trainers"],
  ["soda pop", "soft drink"],
  ["stroller", "pram"],
  ["tailpipe", "exhaust pipe"],
  ["trashcan", "bin"],
  ["zip code", "postcode"],
  ["zucchini", "courgette"],
  ["backhoe", "digger"],
  ["dishrag", "dishcloth"],
  ["drywall", "plasterboard"],
  ["freeway", "motorway"],
  ["grifter", "con man"],
  ["ladybug", "ladybird"],
  ["mailman", "postman"],
  ["realtor", "estate agent"],
  ["rv park", "caravan site"],
  ["scalper", "ticket tout"],
  ["sneaker", "trainer"],
  ["stoolie", "grass"],
  ["takeout", "takeaway"],
  ["tylenol", "paracetamol"],
  ["upscale", "upmarket"],
  ["varmint", "vermin"],
  ["booger", "bogey"],
  ["burlap", "hessian"],
  ["careen", "career"],
  ["catsup", "ketchup"],
  ["cleats", "football boots"],
  ["diaper", "nappy"],
  ["drapes", "curtain"],
  ["eraser", "rubber"],
  ["faucet", "tap"],
  ["jell-o", "jelly"],
  ["mohawk", "mohican"],
  ["rappel", "abseil"],
  ["rugola", "rocket"],
  ["soccer", "football"],
  ["varmit", "vermin"],
  ["zipper", "zip"],
  ["bangs", "fringe"],
  ["condo", "flat"],
  ["drape", "curtain"],
  ["fries", "chips"],
  ["grunt", "squaddie"],
  ["mamma", "mam"],
  ["momma", "mam"],
  ["rif'd", "made redundant"],
  ["scads", "great amounts"],
  ["snuck", "sneaked"],
  ["trash", "rubbish"],
  ["vacay", "hols"],
  ["mama", "mam"],
  ["math", "maths"],
  ["narc", "grass"],
  ["mom", "mum"],
  ["nix", "cancel"],
  ["rif", "redundancy"],
  ["rv", "caravan"]
];
