module.exports = [
  ["provisional driving licence", "learner's permit"],
  ["heath robinson device", "rube goldberg device"],
  ["central reservation", "median strip"],
  ["provisional licence", "learner's permit"],
  ["self-raising flour", "self-rising flour"],
  ["sleeping policeman", "speed bump"],
  ["athletics meeting", "track meet"],
  ["flight lieutenant", "captain"],
  ["washing-up liquid", "dish soap"],
  ["building society", "savings and loan association"],
  ["bureau de change", "currency exchange"],
  ["dual carriageway", "divided highway"],
  ["selling-out shop", "liquor store"],
  ["shopping trolley", "shopping cart"],
  ["sleeping partner", "silent partner"],
  ["swimming costume", "swimsuit"],
  ["approved school", "juvie"],
  ["current account", "checking account"],
  ["driving licence", "driver's license"],
  ["identity parade", "police lineup"],
  ["inverted commas", "quotation marks"],
  ["telephone kiosk", "phone booth"],
  ["turf accountant", "bookie"],
  ["anti-clockwise", "counterclockwise"],
  ["extension lead", "extension cord"],
  ["knacker's yard", "junkyard"],
  ["pillar-box red", "fire engine red"],
  ["poste restante", "general delivery"],
  ["reel of cotton", "spool of thread"],
  ["skirting board", "baseboard"],
  ["suspender belt", "garter belt"],
  ["transport cafe", "truckstop"],
  ["turn-indicator", "turn signal"],
  ["zebra crossing", "crosswalk"],
  ["bits and bobs", "odds and ends"],
  ["black pudding", "blood sausage"],
  ["car boot sale", "swap meet"],
  ["conservatoire", "conservatory"],
  ["drink-driving", "drunk driving"],
  ["electric fire", "space heater"],
  ["group captain", "colonel"],
  ["hire purchase", "installment plan"],
  ["jacket potato", "baked potato"],
  ["agony column", "advice column"],
  ["bank holiday", "public holiday"],
  ["bog-standard", "garden-variety"],
  ["boiled sweet", "hard candy"],
  ["cash machine", "ATM"],
  ["child-minder", "babysitter"],
  ["double first", "undergraduate degree"],
  ["engaged tone", "busy signal"],
  ["estate agent", "real estate agent"],
  ["fairy lights", "Christmas lights"],
  ["fire brigade", "fire department"],
  ["holidaymaker", "vacationer"],
  ["kitchen roll", "paper towels"],
  ["nosey parker", "nosy"],
  ["number plate", "license plate"],
  ["plasterboard", "drywall"],
  ["postal order", "money order"],
  ["perambulator", "stroller"],
  ["quieten down", "quiet down"],
  ["tipping down", "raining hard"],
  ["wing mirrors", "side mirrors"],
  ["accountancy", "accounting"],
  ["answerphone", "answering machine"],
  ["by-election", "special election"],
  ["candidature", "candidacy"],
  ["candy floss", "cotton candy"],
  ["carriageway", "lane"],
  ["clapped out", "clapped out"],
  ["cotton wool", "cotton ball"],
  ["counterfoil", "stub"],
  ["counterpane", "bedspread"],
  ["drawing pin", "thumbtack"],
  ["dustbin man", "garbage man"],
  ["elastoplast", "bandage"],
  ["guard's van", "caboose"],
  ["high street", "main street"],
  ["invigilator", "proctor"],
  ["ironmongery", "hardware store"],
  ["jerry-built", "jerry-rigged"],
  ["jumble sale", "rummage sale"],
  ["launderette", "laundromat"],
  ["nosy parker", "nosy"],
  ["off-licence", "liquor store"],
  ["off-the-peg", "off-the-rack"],
  ["paper round", "paper route"],
  ["paracetamol", "Tylenol"],
  ["pritt-stick", "glue stick"],
  ["smart dress", "formal attire"],
  ["spot of tea", "cup of tea"],
  ["ticket tout", "scalper"],
  ["wage packet", "paycheck"],
  ["chatted up", "flirted"],
  ["cling-film", "plastic wrap"],
  ["cling film", "plastic wrap"],
  ["cotton bud", "cotton swab"],
  ["estate car", "station wagon"],
  ["fairy cake", "cupcake"],
  ["jerrybuilt", "jerry-rigged"],
  ["jump leads", "jumper cables"],
  ["kirby grip", "bobby pin"],
  ["loudhailer", "megaphone"],
  ["mole grips", "vise-grips"],
  ["pernickety", "persnickety"],
  ["petrolhead", "gearhead"],
  ["pillar box", "mailbox"],
  ["pound shop", "dollar store"],
  ["windscreen", "windshield"],
  ["aubergine", "eggplant"],
  ["bone-idle", "lazy"],
  ["cafetière", "French press"],
  ["cafetiere", "French press"],
  ["cashpoint", "ATM"],
  ["chip shop", "fish-and-chip shop"],
  ["clingfilm", "plastic wrap"],
  ["courgette", "zucchini"],
  ["freephone", "toll-free number"],
  ["ice lolly", "popsicle"],
  ["panda car", "police car"],
  ["phone box", "payphone"],
  ["press-ups", "push-ups"],
  ["pushchair", "stroller"],
  ["sellotape", "Scotch tape"],
  ["slowcoach", "slowpoke"],
  ["sun cream", "sunscreen"],
  ["tea towel", "dish towel"],
  ["truncheon", "nightstick"],
  ["bog roll", "roll of toilet paper"],
  ["car boot", "trunk"],
  ["car hire", "car rental"],
  ["car park", "parking lot"],
  ["cobblers", "shoe repairers"],
  ["dogsbody", "grunt"],
  ["draughts", "checkers"],
  ["dustcart", "garbage truck"],
  ["hold-all", "duffel bag"],
  ["ladybird", "ladybug"],
  ["motorway", "freeway"],
  ["oughtn't", "shouldn't"],
  ["overleaf", "reverse"],
  ["plectrum", "guitar pick"],
  ["press-up", "push-up"],
  ["publican", "landlord"],
  ["punch-up", "a fistfight"],
  ["slaphead", "bald man"],
  ["spiffing", "spiffy"],
  ["squaddie", "grunt"],
  ["stockist", "dealer"],
  ["takeaway", "takeout"],
  ["trainers", "sneakers"],
  ["trousers", "pants"],
  ["turn-ups", "cuffs"],
  ["upmarket", "upscale"],
  ["y-fronts", "briefs"],
  ["autocue", "teleprompter"],
  ["brekkie", "breakfast"],
  ["bum bag", "fanny pack"],
  ["cagoule", "windbreaker"],
  ["chancer", "opportunist"],
  ["chat up", "flirt"],
  ["chinwag", "chat"],
  ["chuffed", "pleased"],
  ["chunder", "vomit"],
  ["dustbin", "trash can"],
  ["dustman", "garbage man"],
  ["earthed", "grounded"],
  ["fancy a", "would you like a"],
  ["flypast", "flyby"],
  ["funfair", "carnival"],
  ["gherkin", "pickle"],
  ["rashers", "bacon"],
  ["sat nav", "GPS"],
  ["squidgy", "squishy"],
  ["tipp-ex", "Wite-Out"],
  ["abseil", "rappel"],
  ["advert", "advertisement"],
  ["biccie", "cookie"],
  ["blower", "telephone"],
  ["boffin", "an expert"],
  ["brekky", "breakfast"],
  ["brolly", "umbrella"],
  ["burgle", "burglarize"],
  ["cheeky", "impertinent"],
  ["chippy", "fish-and-chip shop"],
  ["crisps", "potato chips"],
  ["draper", "dry goods"],
  ["footie", "soccer"],
  ["hot up", "heating up"],
  ["learnt", "learned"],
  ["muppet", "an incompetent or foolish person"],
  ["petrol", "gasoline"],
  ["postie", "postman"],
  ["sarnie", "sandwich"],
  ["sannie", "sandwich"],
  ["shan't", "won't"],
  ["slippy", "slippery"],
  ["spawny", "lucky"],
  ["tannoy", "public address system"],
  ["artic", "semi"],
  ["barmy", "balmy"],
  ["bicky", "cookie"],
  ["bikky", "cookie"],
  ["bloke", "guy"],
  ["breve", "double whole note"],
  ["bunce", "a windfall"],
  ["carer", "caregiver"],
  ["cuppa", "cup of tea"],
  ["jemmy", "jimmy"],
  ["lorry", "truck"],
  ["maths", "math"],
  ["nappy", "daiper"],
  ["offie", "liquor store"],
  ["pants", "underwear"],
  ["prang", "fender bender"],
  ["recce", "recon"],
  ["sarky", "snarky"],
  ["sarny", "sandwich"],
  ["skint", "broke"],
  ["telly", "television"],
  ["biro", "ballpoint pen"],
  ["caff", "café"],
  ["cleg", "horse fly"],
  ["daft", "silly"],
  ["dosh", "dough"],
  ["gaol", "jail"],
  ["hols", "holidays"],
  ["nark", "narc"],
  ["pram", "stroller"],
  ["prat", "idiot"],
  ["snog", "kiss"],
  ["twee", "cutesy"],
  ["guv", "governor"],
  ["lav", "toilet"],
  ["loo", "bathroom"],
  ["oap", "senior citizen"],
  ["owt", "anything"],
  ["pub", "bar"],
  ["uni", "college"],
  ["veg", "vegetables"],
  ["ta", "thank you"],
  ["wc", "bathroom"]
];
